### ISSUE TITLE
BESTmcmc suppress console when parallel = true despite verbose = true

### ISSUE THREAD

**Issue by jasanford** [mikemeredith/BEST#5]
As above. The process runs fine and output is correct. Perhaps console output wouldn't be useful but automatic suppression isn't mentioned in the documentation so it feels like a bug.

Versions: R 3.2.2, BEST 0.3.0

Sample script and terminal output:
> BESTout <- BESTmcmc(y1, y2, parallel = TRUE, verbose = TRUE)

Processing function input....... 

Done. 
 
Beginning parallel processing with 3 clusters. Console output will be suppressed.

Looking further into it this may be jagsUI at fault.

**Comment by mikemeredith** [comment]
Thanks for flagging that problem. You are right that this should be made clear in the documentation, and I'll improve that in the next release. V. 0.4.0 has just gone to CRAN, so I'll wait for a few other changes to accumulate before sending a new version.

The problem arises because of the way parallel processing is implemented, which does not allow text output from the workers to be fed back to the master. It might be possible to capture the text and include it in the final output object, but it still wouldn't get back to the master until the run was complete, which would not be very useful.

The `runjags` package does manage to get the output from one chain to the Console in real time. I'm not quite sure how that's done, but I suspect that one chain is run by the master and the rest are passed to the workers. That itself is not simple, as the master normally waits for the workers to complete before continuing, ie, R freezes.

**Comment by jasanford** [comment]
?That makes sense. Thanks for getting back to me so quickly.


Joseph

________________________________
