### ISSUE TITLE
setting priors to default results in model fail

### ISSUE THREAD

**Issue by silberzwiebel** [mikemeredith/BEST#6]
Hi,

I'm trying to set different priors for a paired t-test. Since there is no possibility to specify that the data came from a repeated measure design (i.e, the same subject responded in different conditions and I'm interested whether he/she responded differently. This is different from having two subjects tested in different conditions), I'm using the single group t-test and using as input the difference of the two vectors (and hope this is the way one should/can do this).
Now to the real problem.

Running the model like this works with no errors:
```
y = read.csv("diffC.csv")$x
best = BESTmcmc(y)
```

But specifying the priors using the default priors as stated in `?BESTmcmc` results in an JAGS error:

```
y = read.csv("diffC.csv")$x
p = list(muM = mean(y), muSD = sd(y)*5, sigmaMode = sd(y), sigmaSD = sd(y)*5, nuMean = 30, nuSD = 30)
best = BESTmcmc(y, priors = p)
```

The following JAGS error happens during the adaption:
```
error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: Error in node y[1]
Failure to calculate log density
```

(I originally tried using different priors but then realized it isn't even working for the default priors.)
This looks like a bug to me: Not explicitly specifying priors leads to no error but specifying the default priors leads to an error.

Looking more closely at my data revealed the following:
My data consist of acceptability ratings for a given stimulus. Apparently, there is not much difference between the two conditions: there are a lot of 0s in the data (meaning: the same subject gave the same rating in both conditions).
This makes the histogram of the data having a rather great peak at 0.
My idea what BEST tries to do is fitting a t-distribution on these data. Due to the large peak this results in a non-normal t-distribution (log10nu is around 0.0004 -> nu is roughly 1) with a small SD (sigma around 0.00137). If now the SD gets 0 (or less), JAGS is complaining with the above error. There are, however, not much outlier in the data (I guess this also depends on what you call an outlier ;) ).
I tried to model the same data with a Gaussian likelihood instead of the proposed t-distribution and it works quite well. The normal function is just not really getting the large peak at 0.
So, in the end, this might actually not be a bug in the BEST package (although it seems to use different default priors when one passes no priors at all compared to what is stated in the help), but rather a general issue with the BEST approach fitting my very data. On the other hand: How to use the BEST approach to detect an effect of 0.5 difference in ratings on a rating scale from 1-9 as I'm using?
Any ideas how what likelihood function would best accommodate the data I have? (I'm just starting with Bayesian data analysis -- maybe this is the very crucial question that has no easy answer)

My data for this case can be found for the next two weeks [under this link](https://kartoffelsalat.ddns.net:8001/f/2eb516160c/?raw=1).

**Comment by mikemeredith** [comment]
Hi silberzweibel,

Thanks for flagging the issue. I think this is due to difficulty fitting the model to your data, but you should get an informative error message.

First the priors business. The original versions of BEST used the priors described in Kruschke (2013): a broad normal prior for mu, a wide uniform prior for sigma, and a negative exponential prior for nu. There was no way for the user to set priors, and no `priors` argument to `BESTmcmc`. The current version uses the priors described in Kruschke's blog [here](http://doingbayesiandataanalysis.blogspot.my/2015/04/informed-priors-for-bayesian-comparison.html) but with the constraint on nu relaxed as described [here](http://doingbayesiandataanalysis.blogspot.my/2015/12/prior-on-df-normality-parameter-in-t.html). For backward compatibility, the default is `priors = NULL`, which implements the Kruschke (2013) priors. The alternative is to provide a list with values for each of the 3 parameters in the model, giving centre and spread, so up to 6 elements in the list. mu still has a normal prior, but a gamma prior is used for sigma and nu. Since the user may want to specify priors for only 1 or 2 parameters, default values are provided for all 6 elements in the list. Putting `priors = list()`, an empty list, uses the defaults for all 6 elements. Note that `priors = list()` is *not* equivalent to `priors = NULL`.

A key difference between the old and the current priors relevant to your data is the constraint on nu. Kruschke (2013) had `nu >= 1`, but the current code has `nu >= 0`.

Your data are far from normal, as you can see with `hist(y, freq = FALSE) ; curve(dnorm(x, mean(y), sd(y), add=TRUE)` or with a qq-plot `qqnorm(y) ; qqline(y)`. The median is 0 and 57% of the values are 0. BEST fits a t-distribution to the data, which has 'fat tails' to allow for outliers, but it is still bell-shaped and symetrical. This is not a good description of your data.

When you run `BESTmcmc(y)` (with the old priors), it give nu =1, mu = 0, and sigma is tiny. This is a narrow Cauchy distribution centred on 0; all the non-zero values in y are treated as outliers. The value of nu is affected by the constraint, which limits the fatness of the tails and indirectly limits sigma. This is relaxed when you run `BESTmcmc(y, priors = list())`; all the zero values are *precisely* zero, so it makes sense to have a distribution with sigma = 0 and nu = 0... except that JAGS can't cope with that!

You mention on Rasmus' site that the data are ordinal but you are treating them as metric. That might work if you are lucky; in this case you aren't lucky. You should really do a proper analysis for ordinal data.

It is possible to fit a normal model to your data; that can be done in BEST by setting a strong prior on nu, eg. `BESTmcmc(y, priors = list(nuMean = 1000, nuSD = 1))`, but that isn't really a valid model.

In the next version of BEST I'll expand on the explanations for the priors and see if it helps to keep nu away from zero, perhaps with a minimum of 0.0001.

**Comment by mikemeredith** [comment]
It does seem that the JAGS error is due to the values of exactly 0. When I added a small amount of noise to the data with `y <- y + rnorm(length(y), 0, 0.01` and it worked. nu was 0.3 and mu and sigma were both small.

**Comment by silberzwiebel** [comment]
Thanks for the detailed explanation! I took your advice and modeled the data treating as ordinal data instead of metric data. Since I can't easily do this with your package, I moved on to the `brms`package and used the following command:

`brm(Rating ~ condition + (1 | subject), family = cumulative(link = "logit"), data = y)`

This works perfectly. Do you plan to support different kinds of data in the BEST package? If I got this correctly, you would need to change then the t distribution with the cumulative distribution. I think this would highlight another benefit of Bayesian statistics: The idea is the same, you just use some other distributions here and there.

Regarding the failure with JAGS and `nu==0`: At the end of the day, this seems to me as a bug in JAGS (or at least a highly undesirable feature). In my opinion JAGS shouldn't crash on this but give (severe) warnings that something seems odd with the model. Then you would still get some results and might see where the problem actually is (instead of just getting a hard-to-interpret error message). But I guess you can't change JAGS here and this should be posted on JAGS issue tracker.

**Comment by mikemeredith** [comment]
BEST aims to provide an alternative to the frequentist t-test, which itself assumes that the data are samples drawn from a normally-distributed variable in the population. It is more robust to outliers as it uses a t-distribution instead of a normal distribution, but that's as far as we want to go. Other packages out there provide alternatives!

JAGS is a general-purpose MCMC engine capable of running very complex models. So `Error in node y[1]: Failure to calculate log density` is as good as it gets, can't expect JAGS to analyse the model.

**Comment by mikemeredith** [comment]
Devel version 0.4.0.9000 has constraints `sigma > 0.0001` and `nu > 0.0001` and no longer produces an error from JAGS with your data. The posterior mean of `sigma` is 0.0001, which is a pretty nonsensical model, given that your data range from -7 to +4.
